-- CREATION DES TABLES VIA LES REQUETES

SET SEARCH_PATH = "C_OPE";
DROP TABLE IF EXISTS "tb_contacts";
CREATE TABLE "tb_contacts" (
    "id" SERIAL,
    "nom" VARCHAR(100) NOT NULL,
    "prenom" VARCHAR(100) NOT NULL,
    "telephone" VARCHAR(25) UNIQUE NOT NULL,
    "email" VARCHAR(100) UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "tb_contacts_PKEY" PRIMARY KEY ("id")
);