-- CREATION DES TABLES VIA LES REQUETES

SET SEARCH_PATH = "api_contacts_cli_prod";
DROP TABLE IF EXISTS "TB_USERS";
CREATE TABLE "TB_USERS" (
    "id_user" SERIAL,
    "nom" VARCHAR(100) NOT NULL,
    "prenom" VARCHAR(100) UNIQUE NOT NULL,
    "telephone" VARCHAR(25) UNIQUE NOT NULL,
    "email" VARCHAR(100) UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TB_USERS_PKEY" PRIMARY KEY ("id_user")
);